version: '3'
services:
  mariadb:
    restart: always
    image: mariadb:10.5
    expose: 
      - 3306
    environment: 
      MYSQL_DATABASE: hv_live_demo
      MYSQL_ROOT_PASSWORD: demopwd
      TZ: Asia/Shanghai
    volumes: 
      - /var/docker-data/mariadb:/var/lib/mysql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
  server:
    restart: always
    image: hvlive/demo-server:latest
    ports: 
      - 10050:8080
    links: 
      - mariadb:mariadb
    command: 
      - java
      - -Djava.security.egd=file:/dev/./urandom
      - -Duser.timezone=GMT+08
      - -jar
      - /app.jar
      - --spring.datasource.url=jdbc:mysql://mariadb:3306/hv_live_demo?serverTimezone=UTC&characterEncoding=UTF-8
      - --spring.datasource.password=demopwd
  web:
    restart: always
    image: hvlive/demo-web:latest
    ports: 
      - 10051:80
  live:
    restart: always
    image: hvlive/demo-nginx-live:latest
    ports: 
      - 10052:1935
      - 10053:80
